export const products = [
  {
    id: 1,
    name: 'Packed Tea',
    tags: 'Darjeeling · Assam CTC · Green Tea · Masala Chai',
    description: 'Premium loose-leaf and packed teas from Darjeeling hills, Assam plains, and Nilgiri estates. Available in 100g, 250g, and 500g packs. Rich in antioxidants.',
    price: 'Starting ₹120',
    image: '/images/packed_tea.png',
    badge: 'POPULAR',
    badgeClass: 'badge-popular',
    category: 'tea',
  },
  {
    id: 2,
    name: 'Coffee',
    tags: 'Filter Coffee · Arabica Beans · Instant · Chicory Blend',
    description: 'Handpicked beans from Coorg and Chikmagalur. South Indian filter coffee powder, single-origin roasts, and traditional chicory blends.',
    price: 'Starting ₹150',
    image: '/images/coffee.png',
    category: 'coffee',
  },
  {
    id: 3,
    name: 'Chocolates',
    tags: 'Dark · Milk · White · Truffles · Cocoa Nibs',
    description: 'Artisan Indian chocolates made from single-origin cocoa. Dark chocolate bars (72% cocoa), milk chocolate truffles, and premium gift hampers.',
    price: 'Starting ₹80',
    image: '/images/chocolates.png',
    badge: 'GIFTING',
    badgeClass: 'badge-gifting',
    category: 'chocolates',
  },
  {
    id: 4,
    name: 'Spices',
    tags: 'Turmeric · Chili · Cumin · Coriander · Cardamom · Pepper',
    description: 'Stone-ground, sun-dried single spices from Kerala, Rajasthan, and Tamil Nadu. No artificial colours, no fillers. Lab-tested for purity.',
    price: 'Starting ₹45',
    image: '/images/spices.png',
    badge: 'BESTSELLER',
    badgeClass: 'badge-bestseller',
    category: 'spices',
  },
  {
    id: 5,
    name: 'Ready to Cook Packs',
    tags: 'Curry Kits · Dal Mixes · Biryani Masala · Sambar Powder',
    description: 'Authentic meal kits — just add vegetables! Includes pre-measured spice blends for paneer butter masala, chole, dal tadka, and more.',
    price: 'Starting ₹60',
    image: '/images/ready_to_cook.png',
    category: 'ready-to-cook',
  },
  {
    id: 6,
    name: 'Ready to Eat Snacks',
    tags: 'Namkeen · Mixture · Murukku · Banana Chips · Sev',
    description: 'Traditional Indian snacks made with cold-pressed oils. Crunchy namkeen, chakli, ribbon pakoda, and masala peanuts. Perfect for tea-time.',
    price: 'Starting ₹40',
    image: '/images/ready_to_eat.png',
    category: 'snacks',
  },
  {
    id: 7,
    name: 'Bulk Spices & Lentils',
    tags: 'Toor Dal · Moong Dal · Chana Dal · Masoor · Urad Dal',
    description: 'Farm-sourced lentils and whole spices in 1kg, 5kg, and 10kg bags. Cleaned, sorted, and polished. High protein content.',
    price: 'Starting ₹90/kg',
    image: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=600&auto=format&fit=crop&q=80',
    badge: 'BULK',
    badgeClass: 'badge-bulk',
    category: 'bulk',
  },
  {
    id: 8,
    name: 'Bulk Spice Blends',
    tags: 'Garam Masala · Sambar · Rasam · Biryani · Tandoori',
    description: 'Signature blends using 8–15 whole spices, dry-roasted and stone-ground. No added salt or MSG. Recipes perfected over generations.',
    price: 'Starting ₹75',
    image: 'https://images.unsplash.com/photo-1506368249639-73a05d6f6488?w=600&auto=format&fit=crop&q=80',
    category: 'spices',
  },
  {
    id: 9,
    name: 'Traditional Pappads',
    tags: 'Urad · Moong · Sabudana · Masala · Lijjat-style',
    description: 'Handmade sun-dried pappads and appalam from Rajasthan and South India. Crispy, flavourful, and preservative-free.',
    price: 'Starting ₹50',
    image: 'https://images.unsplash.com/photo-1601050690117-94f5f6fa8bd7?w=600&auto=format&fit=crop&q=80',
    category: 'traditional',
  },
  {
    id: 10,
    name: 'Traditional Rice Varieties',
    tags: 'Basmati · Sona Masoori · Ponni · Red Rice · Black Rice',
    description: 'Aged basmati from Punjab, Sona Masoori from Andhra, heritage red and black rice. Rich in fibre and micronutrients.',
    price: 'Starting ₹70/kg',
    image: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=600&auto=format&fit=crop&q=80',
    badge: 'PREMIUM',
    badgeClass: 'badge-premium',
    category: 'bulk',
  },
];

export const testimonials = [
  {
    id: 1,
    text: '"The spices from Foods of Passion are so fresh — you can actually smell the difference. My sambar has never tasted this good. I\'ve been buying turmeric and red chili here for 2 years now."',
    name: 'Priya Sharma',
    role: 'Home Cook, Bangalore',
    initial: 'P',
  },
  {
    id: 2,
    text: '"We order bulk lentils and rice for our restaurant. The quality is consistently excellent — toor dal cooks perfectly every time. Their prices are very competitive."',
    name: 'Rajesh Kumar',
    role: 'Restaurant Owner, Chennai',
    initial: 'R',
  },
  {
    id: 3,
    text: '"I discovered their Darjeeling first flush tea and I\'m addicted! The ready-to-cook packs are a lifesaver for weeknight dinners — authentic taste without the hassle."',
    name: 'Anitha Nair',
    role: 'Tea Enthusiast, Kochi',
    initial: 'A',
  },
];

export const benefits = [
  { icon: '🌾', title: 'Farm to Shelf', text: 'Direct sourcing from 200+ farmers across Kerala, Rajasthan, Assam, Tamil Nadu & more — no middlemen.' },
  { icon: '🔬', title: 'Purity Guaranteed', text: 'Every batch is tested for pesticides, heavy metals, allergens & adulterants. FSSAI compliant and certified.' },
  { icon: '📦', title: 'Fresh Packaging', text: 'Nitrogen-flushed, UV-protected pouches keep spices aromatic and snacks crunchy for months.' },
  { icon: '💰', title: 'Honest Pricing', text: 'Bulk and retail options at fair prices. No hidden charges. Volume discounts for restaurants and caterers.' },
];

export const stats = [
  { value: '10+', label: 'Product Categories' },
  { value: '500+', label: 'Happy Customers' },
  { value: '100%', label: 'Natural & Pure' },
  { value: '50+', label: 'Trusted Brands' },
];
